### ISSUE TITLE
Need to fix crash bug when using ADFGVX cipher from menu

### ISSUE THREAD

**Issue by Crossroadsman** [Crossroadsman/treehouse-techdegree-python-project2#5]
Note that the built-in tests for ADFGVX work so the error may be in how secret_messages.py initialises the ADFGVX cipher.

Examples of crashing inputs:
- plaintext: 'the quick brown fox jumps over the lazy dog'
- pad: None
- key: 'hello'
- grouping: 0, 5

Crash result:
```
Traceback (most recent call last):
  File "secret_messages.py", line 200, in <module>
    processed_text = cipher.encrypt(text)
  File "/Users/AlexKoumparos/Desktop/treehouse-techdegree-python-project2/adfgvx.py", line 30, in encrypt
    self._populate_keyphrase_columns()
  File "/Users/AlexKoumparos/Desktop/treehouse-techdegree-python-project2/adfgvx.py", line 145, in _populate_keyphrase_columns
    self.keyphrase_columns[i].append(character_pair[0])
TypeError: 'NoneType' object is not subscriptable
```

At least part of the problem involves some of the characters in the plaintext not being correctly looked up in the table (the polybius square is being correctly populated with custom values and the plaintext passed in from the menu appears intact). However, certain characters are mapping to None instead of their pairs, at least `i` and `j` (which are combined characters in the default 5x5 polybius square)

**Comment by Crossroadsman** [comment]
See commit: 1a9e0fa

Probably fixed but need to complete testing.
